### PR TITLE
fix: improve error message for duplicated file

### LINKED ISSUE #127: Duplicate filename, but what?
I'm getting this error:

```
invalid Zip archive: Duplicate filename
```

but I cannot understand what is the file duplicated.

Is it possible to write the filename in the error?

### PR DESCRIPTION
**Pull request by Bogay**
This RP include duplicated filename in returned `ZipResult`. Also introduce a macro `invalid!` to help construct `ZipError::InvalidArchive`.

Close #127

### CODE REVIEW

File: src/write.rs [hunk 1]
```diff
@@ -668,7 +666,7 @@ impl<A: Read + Write + Seek> ZipWriter<A> {
     pub fn deep_copy_file(&mut self, src_name: &str, dest_name: &str) -> ZipResult<()> {
         self.finish_file()?;
         if src_name == dest_name || self.files.contains_key(dest_name) {
-            return Err(InvalidArchive("That file already exists"));
+            return Err(invalid!("That file already exists"));
```
Comment (Bogay) [inline src/write.rs:669]: Should I also add `dest_name` to error message?

**Review by Pr0methean — DISMISSED** [review]

**Review by Pr0methean — APPROVED** [review]
Great, thanks!
