### PR TITLE
fix: rewrite the EOCD/EOCD64 detection to fix extreme performance regression

### LINKED ISSUE #231: Regression: opening large zip files is slow since 2.1.4 because the entire file is scanned
**Describe the bug**

I have a 266 MB zip file, from which I only need to extract a 1 kB file. The rest of the files in the archive are irrelevant at this stage in the program.

However, opening the zip file using `ZipArchive::new(file)` takes about 7 seconds. It's a lot faster the second time round, because of Linux's filesystem cache.

I traced the root cause to `Zip32CentralDirectoryEnd::find_and_parse`, which locates the "end of central directory record" very quickly at the end of the file, but then keeps scanning backwards through the entire file to find another one.

**To Reproduce**

Have a large zip file:

```
$ ls -lh archive.zip
-rw-r--r-- 1 thomas thomas 266M Aug  8 12:20 archive.zip
$ cargo build --release
$ echo 3 | sudo tee /proc/sys/vm/drop_caches  # Flush filesystem cache (Linux only)
$ time target/release/repro
real	0m6.714s
user	0m0.560s
sys	0m1.293s
```

Use this as the main program:

```
fn main() {
    let file = std::fs::File::open("archive.zip").unwrap();
    let archive = zip::ZipArchive::new(file).unwrap();
}
```

**Expected behavior**

Extracting a single 1 kB file from a large archive should be possible quickly. `unzip` can do it:

```
$ echo 3 | sudo tee /proc/sys/vm/drop_caches
$ time unzip -l archive.zip
Archive:  archive.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
...
---------                     -------
1228949561                     9 files

real	0m0.012s
user	0m0.005s
sys	0m0.000s
$ echo 3 | sudo tee /proc/sys/vm/drop_caches
$ time unzip archive.zip some_file.txt
Archive:  archive.zip
  inflating: some_file.txt           

real	0m0.012s
user	0m0.000s
sys	0m0.005s
```

**Version**

zip 2.1.6. This is also happening in 2.1.4, but not in 2.1.3. I think cb2d7abde7863a4ce01dbac5b3b48b4006e60599 or 9bf914d7d41842b381d303becf5364b5b2b8c1f2 is the cause, but I haven't dug deeper.

### PR DESCRIPTION
**Pull request by RisaI**
In this PR, a new way of finding the EOCD/EOCD64 blocks is introduced. The motivation is to fix the extreme performance regression introduced in https://github.com/zip-rs/zip2/commit/cb2d7abde7863a4ce01dbac5b3b48b4006e60599. This PR is also expected to close #231.

## What was wrong

In the previous iteration, the `ZipArchive::get_metadata` function scanned the entire contents of the archive (in extreme cases multiple times) and contained some amount of backtracking even in the best case scenario of no prepended junk data. There was also a lot of code duplication in the functions for finding EOCD and EOCD64 blocks.

## What this PR introduces

A `MagicFinder` pseudo-iterator is implemented for generic magic needle search from the end of a seekable reader. An additional `OptimisticMagicFinder` is implemented for the best case scenario, where the archive offset is either known exactly or is equal to zero, so that no scanning is performed, as it would be unnecessary.

The `find_and_parse` methods of `Zip32CentralDirectoryEnd` and `Zip64CentralDirectoryEnd` are replaced with a common `find_central_directory` function. The function employs the following strategy to locate EOCD and EOCD64 if it is expected to be present:

* A `MagicFinder` is used to find EOCD magic bytes
* The EOCD block is parsed and it's internal validity is checked, discarding the entry if it's invalid
* It is determined whether the EOCD contents indicate the file is ZIP64
* In the ZIP32 case:
  * An empty archive is assumed to always be correct and is returned
  * A non empty archive attempts to look for the first CDFH between the relative offset in EOCD and the EOCD offset
  * If found, the archive offset is determined and the entry is returned, otherwise it is discarded
* In the ZIP64 case:
  * The EOCD64 Locator is parsed at it's expected position
  * Its internal validity is checked
  * EOCD64 magic bytes are searched for between the relative offset in the Locator and Locator's own offset
  * If EOCD64 is found and is internally valid, the archive offset is determined and the EOCD + EOCD64 are returned

The code for `get_metadata` was simplified, because additional information is now available after finding the EOCDs (the archive offset in particular).

## Performance

In my internal testing (reading a 44MB ZIP with 30 files to obtain the file count), the extreme performance regression is gone, while still satisfying all of the tests.

```
2.1.3: ~6.2ms
2.2.0: ~14s
This PR: ~13.5ms
```

Clearly there are still some performance regressions left, but according to my testing, the code path I spent optimizing takes only 0.3ms out of the 13.5ms, so the regression must lie elsewhere.

## What remains to be done

- [ ] get feedback for the EOCD/CFHD naming convention in ZipErrors
- [ ] deprecating the `ArchiveOffset::FromCentralDirectory` option?
- [x] reconciling EOCD and EOCD64 archive comments

### Naming conventions for byte blocks

In this PR I use the original naming convention for the different type of blocks (End Of Central Directory instead of Central Directory End, etc.). If this is wrong, please, let me know, I will revert this. If you'd like me to change the rest of the errors to match the official convention, I'd also be happy to do that.

### `ArchiveOffset::FromCentralDirectory`  deprecation

This option was previously respected for ZIP32 only, but the logic did not make much sense to me. GitHub search reveals that there is not public repository using this option. Could you, please, clarify, what the intent with this feature was? The way I see it, it's enough to have an option to do offset detection if the initial guess fails and also to have the `Known` variant to opt-out of the detection mechanism.

### Archive comments duality

Previously, this PR introduced a breaking change, where the `ZipArchive` comment for ZIP64 is now read from EOCD64 instead of EOCD. Instead, I introduced the `zip64_comment` field in `Shared` and made the field available separately. Now both can be used by the users and it should be clear which is which.

### CODE REVIEW

File: src/read.rs [hunk 1]
```diff
@@ -56,6 +54,8 @@ pub(crate) mod zip_archive {
         // This isn't yet used anywhere, but it is here for use cases in the future.
         #[allow(dead_code)]
         pub(super) config: super::Config,
+        pub(crate) comment: Box<[u8]>,
```
Comment (Pr0methean) [inline src/read.rs:57]: Can this be an `Option` as well?

File: src/read.rs [hunk 2]
```diff
@@ -549,264 +597,20 @@ impl<R: Read + Seek> ZipArchive<R> {
...
-                .chain(invalid_errors_32)
-                .chain(invalid_errors_64)
-                .next()
-                .unwrap());
-        };
-        reader.seek(SeekFrom::Start(shared.dir_start))?;
-        Ok((Rc::try_unwrap(footer).unwrap(), shared.build()))
+    pub(crate) fn get_metadata(config: Config, reader: &mut R) -> ZipResult<Shared> {
+        // Find the EOCD and possibly EOCD64 entries and determine the archive offset.
+        let cde = spec::find_central_directory(reader, config.archive_offset)?;
```
Comment (Pr0methean) [inline src/read.rs:604]: What happens if something that looks like a valid EOCD or EOCD64 block, but doesn't have a valid central directory in front of it and thus fails `try_from`, is included in the file comment of a valid ZIP file? We should keep looking for the real one in that case.

File: src/read/magic_finder.rs [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+}
+
+impl<'a> MagicFinder<'a> {
+    /// Create a new magic bytes finder to look within specific bounds.
+    pub fn new(magic_bytes: &'a [u8], bounds: (u64, u64)) -> Self {
+        const BUFFER_SIZE: usize = 2048;
+
+        // Smaller buffer size would be unable to locate bytes.
+        // Equal buffer size would stall (the window could not be moved).
+        debug_assert!(BUFFER_SIZE > magic_bytes.len());
```
Comment (Pr0methean) [inline src/read/magic_finder.rs:25]: Should actually be `2 * BUFFER_SIZE - 1`, to ensure that if the entire magic couldn't fit into the window before shifting the window, it can afterward.

File: src/read/magic_finder.rs [hunk 4]
```diff
@@ -0,0 +1,191 @@
...
+    buffer: Box<[u8]>,
+    pub(self) finder: FinderRev<'a>,
+    cursor: u64,
+    mid_buffer_offset: Option<usize>,
+    bounds: (u64, u64),
+}
+
+impl<'a> MagicFinder<'a> {
+    /// Create a new magic bytes finder to look within specific bounds.
+    pub fn new(magic_bytes: &'a [u8], bounds: (u64, u64)) -> Self {
```
Comment (Pr0methean) [inline src/read/magic_finder.rs:20]: Split this into two parameters, `start_inclusive` and `end_exclusive`, for readability.

File: src/read/magic_finder.rs [hunk 5]
```diff
@@ -0,0 +1,191 @@
...
+
+    /// Find the next magic bytes from the end of the reader.
+    ///
+    /// Similar in functionality to a double ended iterator, except
+    /// it propagates errors first and doesn't hold on to the reader
+    /// between items.
+    pub fn next_back<R: Read + Seek>(&mut self, reader: &mut R) -> ZipResult<Option<u64>> {
+        loop {
+            if self.cursor < self.bounds.0 {
+                // The finder is consumed
```
Comment (Pr0methean) [inline src/read/magic_finder.rs:64]: Should actually be `self.cursor <= self.bounds.0`, since we set them equal at the end.

File: src/read/magic_finder.rs [hunk 6]
```diff
@@ -0,0 +1,191 @@
...
+                }
+            }
+
+            // If a match is not found, but the initial guess was mandatory, return an error.
+            if mandatory {
+                return Ok(None);
+            }
+        }
+
+        self.inner.next_back(reader)
```
Comment (Pr0methean) [inline src/read/magic_finder.rs:189]: Will this keep returning the same result if `next_back` is called again? It looks to me like it will (an off-by-one error).

File: src/spec.rs [hunk 7]
```diff
@@ -578,94 +509,13 @@ impl Zip64CentralDirectoryEnd {
...
-            Err(ZipError::InvalidArchive(
-                "Could not find ZIP64 central directory end",
-            ))
-        } else {
-            Ok(results)
-        }
-    }
-
-    pub fn block(self) -> Zip64CDEBlock {
+    pub fn block_and_comment(self) -> (Zip64CDEBlock, Box<[u8]>) {
```
Comment (Pr0methean) [inline src/spec.rs:516]: Start this name with `into_`, since the method consumes `self`.

File: src/spec.rs [hunk 8]
```diff
@@ -674,25 +524,234 @@ impl Zip64CentralDirectoryEnd {
...
-        self.block().write(writer)
+        let (block, comment) = self.block_and_comment();
+        block.write(writer)?;
+        writer.write_all(&comment)?;
+        Ok(())
+    }
+}
+
+pub(crate) struct CentralDirectoryEndInfo {
+    pub eocd: (Zip32CentralDirectoryEnd, u64),
```
Comment (Pr0methean) [inline src/spec.rs:556]: Split this into two fields for readability.

File: src/spec.rs [hunk 9]
```diff
@@ -674,25 +524,234 @@ impl Zip64CentralDirectoryEnd {
...
+
+/// Finds the EOCD and possibly the EOCD64 block and determines the archive offset.
+///
+/// In the best case scenario (no prepended junk), this function will not backtrack
+/// in the reader.
+pub fn find_central_directory<R: Read + Seek>(
+    reader: &mut R,
+    archive_offset: ArchiveOffset,
+) -> ZipResult<CentralDirectoryEndInfo> {
+    const EOCD_SIG_BYTES: [u8; mem::size_of::<Magic>()] =
```
Comment (Pr0methean) [inline src/spec.rs:570]: Do these constants still need to exist in `u32` form? I don't think so.

File: src/spec.rs [hunk 10]
```diff
@@ -342,92 +343,16 @@ impl Zip32CentralDirectoryEnd {
...
-    }
-
     pub fn write<T: Write>(self, writer: &mut T) -> ZipResult<()> {
         let (block, comment) = self.block_and_comment()?;
         block.write(writer)?;
         writer.write_all(&comment)?;
         Ok(())
     }
+
+    pub fn is_zip64(&self) -> bool {
```
Comment (Pr0methean) [inline src/spec.rs:353]: Call this `may_be_zip64` instead, because a ZIP32 file may happen to have u16::MAX files or u32::MAX bytes before the central directory.

File: src/spec.rs [hunk 11]
```diff
@@ -674,25 +524,234 @@ impl Zip64CentralDirectoryEnd {
...
+                });
+            }
+
+            // Consistency check: the CD relative offset cannot be after the EOCD
+            if relative_cd_offset >= eocd_offset {
+                parsing_error = Some(ZipError::InvalidArchive("Invalid CDFH offset in EOCD"));
+                continue;
+            }
+
+            // Attempt to find the first CDFH
```
Comment (Pr0methean) [inline src/spec.rs:627]: Don't you mean the last one?

File: src/spec.rs [hunk 12]
```diff
@@ -674,25 +524,234 @@ impl Zip64CentralDirectoryEnd {
...
+        };
+
+        // ! Relaxed (inequality) due to garbage-after-comment Python files
+        // Consistency check: the EOCD comment must terminate before the end of file
+        if eocd.zip_file_comment.len() as u64 + eocd_offset + 22 > file_length {
+            parsing_error = Some(ZipError::InvalidArchive("Invalid EOCD comment length"));
+            continue;
+        }
+
+        // Branch out for zip32
```
Comment (Pr0methean) [inline src/spec.rs:608]: Handle the case of u16::MAX files in a ZIP32 I mentioned above. This may mean changing `is_zip64()` to return a yes/no/maybe enum.

**Review by Pr0methean — COMMENTED** [review]
Looks like this is on the right track; please fix the failing tests.

File: src/read/magic_finder.rs (hunk 5 above)
Comment (RisaI) [reply src/read/magic_finder.rs:64]: `self.cusor == self.bounds.0` is a valid state. It is achievable by having data of size `BUFFER_SIZE + (BUFFER_SIZE - MAGIC_SIZE + 1) * n` for some `n`. What we set equal at the end are the bounds, to essentially make it a cusor in an empty region.

File: src/read/magic_finder.rs (hunk 6 above)
Comment (RisaI) [reply src/read/magic_finder.rs:189]: There are three cases:
1. no `initial_guess`, the iteration behaves exactly as the inner `MagicFinder`
2. an `initial_guess` is provided and a match is found. The `initial_guess` it destroyed by calling `take()` on it and the finder is converted to case 1
3. no `initial_guess` is provided and no match is found:
    * in the case of a mandatory guess, the iterator terminates (returns `Ok(None)`)
    * in the case of an optional guess, the initial guess falls through. On the next iteration, it will however attempt to check the initial guess again. I will fix this by calling a `take()` in this case, then it will convert to case 1 without making an additional false lookup per iteration.

File: src/read/magic_finder.rs (hunk 3 above)
Comment (RisaI) [reply src/read/magic_finder.rs:25]: On each windows pass, the cursor is moved by `BUFFER_SIZE - magic_bytes.len()` back, so it will contain magic bytes at the boundary. Looking at it now, we actually must move the window by `BUFFER_SIZE - magic_bytes.len() + 1` to not count magic bytes exactly at the start of the window twice. The actuall assertion for the window to move should then be `BUFFER_SIZE >= magic_bytes.len()`.

File: src/spec.rs (hunk 7 above)
Comment (RisaI) [reply src/spec.rs:516]: I was following the existing terminology used in `Zip32CentralDirectoryEnd`. I will also change that function name to `try_into_` as it returns a `ZipResult`.

File: src/spec.rs (hunk 9 above)
Comment (RisaI) [reply src/spec.rs:570]: Yeah, having it represented as a u32 makes it so that you have to manually call conversion functions which is entirely unnecessary, because the magic must always be little-endian. I will submit another PR for this, because it is a bit out of scope.

File: src/read.rs (hunk 1 above)
Comment (RisaI) [reply src/read.rs:57]: I think this is unnecessary. Technically, the comment section is always present, however it can have length zero. This is a state that can be represented by an empty box slice. The ZIP64 comment, however, might not be present at all (when it's actually a ZIP32), so there the distinction makes sense.

File: src/spec.rs (hunk 8 above)
Comment (RisaI) [reply src/spec.rs:556]: I'll rather introduce `DataWithPosition<T>` to keep it as a single field, because the `eocd64` is an `Option` and having to match two `Option`s when they both must be either `Some` or `None` at the same time would be tedious.

File: src/spec.rs (hunk 11 above)
Comment (RisaI) [reply src/spec.rs:627]: Yeah, this might actually be an error in the algorithm, because what I should be looking for is the first file (to correctly determine the archive offset). No idea how this gets past the tests, I will look into this.

**Comment by RisaI** [comment]
The tests in CI seem to fail due to clippy lints enforce in the parts of the codebase I did not even touch. The same seems to happen to other PRs in this repository. At a first glance, this is caused by a few clippy defaults being changed in nightly. I will submit another PR to resolve those and then I'll rebase this branch on that one.

File: src/read.rs (hunk 2 above)
Comment (RisaI) [reply src/read.rs:604]: I'll wrap this in a loop and allow the `find_central_directory` function to continue from the previous EOCD candidate backwards.

File: src/spec.rs (hunk 12 above)
Comment (RisaI) [reply src/spec.rs:621]: If we support these edge cases, then the function can only return maybe/no, because it cannot verify the zip is actually zip64 locally. Changing the name of the function to `may_be_zip64` sounds like the better option.

File: src/spec.rs (hunk 11 above)
Comment (RisaI) [reply src/spec.rs:640]: Yes, this is incorrect, the reason the test pass is that the initial guess is always right. I will add a test case where this is not true.

Comment (RisaI) [reply src/spec.rs:640]: I ended up implementing both directions for the MagicFinder and implemented the correct search direction. I think the only thing remaining is the may_be_zip64 logic for edge case zip32s.

File: src/spec.rs (hunk 7 above)
Comment (RisaI) [reply src/spec.rs]: After investigating this further, I moved the comment length check from the `try_into_block_and_comment` to the write function, because it was very unusual to have it placed where it was. Now both EOCD32/64 have similar signatures for this function and the responsibility to not load oversized comments was moved to the `parse` functions and to not store them to the `write` functions.

**Comment by wolfv** [comment]
This has helped a user pretty greatly when extracting from an network file share (NFS) - I believe `seek's` are very expensive on NFS. Here is the before and after: https://github.com/prefix-dev/rattler-build/issues/1045#issuecomment-2449833158

**Comment by RisaI** [comment]
Alright, I finally got to finish the edge case ZIP32 detection. This caused the fuzzer to detect some cases where the library would try to allocate too much data. I handled this by adding an EOCD64 consistency check that invalidates the entry if the number of files would not fit in the central directory. If the tests pass, I think all of the features are now implemented.

**Review by Pr0methean — DISMISSED** [review]

**Comment by RisaI** [comment]
@Pr0methean I am unable to replicate the clippy errors that are present in the merge queue CI run. Any idea what's wrong?

**Comment by Pr0methean** [comment]
Make sure you're running against the nightly toolchain.

**Comment by RisaI** [comment]
This is, again, unrelated to the code in this branch. I'll submit a new PR.

**Comment by RisaI** [comment]
@Pr0methean There was a race with #255 in the merge queue, because that PR tweaked code that is removed by this PR. I merged with master again, so now it should pass.

**Comment by nickbabcock** [comment]
I tried this PR on a 200GB zip file (233899 files within) that I access over a networked share.

I wanted to report back that this PR falls short of v2.1.3 performance which can start processing individual files immediately (and this PR still takes several orders of magnitude longer to start processing).

This isn't to block the good work here, but perhaps closing #231 is too aggressive

**Review by Pr0methean — APPROVED** [review]

**Comment by Its-Just-Nans** [comment]
@RisaI 

Where does the zip64 comment is from ?



Linked with #436
